# Generated by Django 3.2.9 on 2021-12-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
